name = "clairvora"
compatibility_date = "2025-01-07"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "clairvora"
database_id = "" # Will be filled after creating the database
